app/connectors/DesConnector.scala, app/utils/HeaderCarrierSyntax.scala, project/AppDependencies.scala, project/plugins.sbt, test/connectors/httpParsers/DESParserSpec.scala, test/models/DesErrorBodyModelSpec.scala
=> SASS-679 - Upgraded play to 2.8.8

project/build.properties
=> SASS-000 - Upgraded sbt to 1.4.9

app/connectors/httpParsers/CreateOrAmendDividendsHttpParser.scala, it/connectors/CreateOrAmendDividendsConnectorSpec.scala, project/AppDependencies.scala, project/plugins.sbt, test/controllers/predicates/AuthorisedActionSpec.scala
Aligned API-1390 (Create/update Income source) to version 2.1.0
[SASS-1162](https://jira.tools.tax.service.gov.uk/browse/SASS-1162)
=> SASS-1162 : updated API-1390 to align with version 2.1.0

app/config/AppConfig.scala, it/connectors/CreateOrAmendDividendsConnectorSpec.scala, it/connectors/SubmittedDividendsConnectorSpec.scala, project/AppDependencies.scala, test/config/MockAppConfig.scala, test/connectors/DesConnectorSpec.scala, test/utils/TestUtils.scala
Removing injection from unit tests
[SASS-739](https://jira.tools.tax.service.gov.uk/browse/SASS-739)
=> Sass 1613 - Removing injection from unit tests

project/AppDependencies.scala
[SASS-2960](https://jira.tools.tax.service.gov.uk/browse/SASS-2960)
=> SASS-2960 - Update bootstrap-BE/FE-play-28 dependencies #1

app/controllers/predicates/AuthorisedAction.scala, conf/application.conf, test/controllers/predicates/AuthorisedActionSpec.scala, test/utils/TestUtils.scala
Increasing the minimum Confidence Level value to 250 rather than 200
SASS-3946 https://jira.tools.tax.service.gov.uk/browse/SASS-3946
=> SASS-3946 Increase the 'Confidence Level' to 250 from 200

app/controllers/predicates/AuthorisedAction.scala, app/models/CreateOrAmendDividendsModel.scala, build.sbt, conf/application-json-logger.xml, project/AppDependencies.scala, project/plugins.sbt
Update the dependencies for Dividends
[SASS-4350](https://jira.tools.tax.service.gov.uk/browse/SASS-4350)
=> SASS-4350 Update the dependencies for Dividends

app/connectors/CreateUpdateStockDividendsIncomeConnector.scala, conf/application.conf
[SASS-4004](https://jira.tools.tax.service.gov.uk/browse/SASS-4004)
=> SASS-4004: Navigation of "UK companies" UK Dividends

app/connectors/CreateUpdateStockDividendsIncomeConnector.scala, app/connectors/httpParsers/CreateUpdateStockDividendsIncomeHttpParser.scala, app/controllers/CreateUpdateDividendsIncomeController.scala, app/services/CreateOrAmendDividendsService.scala, app/services/CreateUpdateDividendsIncomeService.scala, app/services/SubmittedDividendsService.scala, app/utils/TaxYearUtils.scala, conf/application.conf, it/connectors/CreateUpdateAnnualIncomeSourceConnectorSpec.scala, it/connectors/GetAnnualIncomeSourcePeriodConnectorSpec.scala, project/AppDependencies.scala, project/plugins.sbt, test/controllers/CreateUpdateDividendsIncomeControllerSpec.scala, test/controllers/SubmittedDividendsIfControllerSpec.scala, test/services/CreateOrAmendDividendsServiceSpec.scala, test/services/CreateUpdateDividendsIncomeServiceSpec.scala, test/services/SubmittedDividendsServiceSpec.scala, test/utils/TaxYearUtils.scala
[SASS-5051](https://jira.tools.tax.service.gov.uk/browse/SASS-5051)
=> SASS-5051 Implement TYS APIs to handle future tax years

app/connectors/CreateUpdateStockDividendsIncomeTYSConnector.scala, app/connectors/DeleteDividendsIncomeDataTYSConnector.scala, app/connectors/GetDividendsIncomeTYSConnector.scala, app/connectors/httpParsers/DeleteDividendsIncomeTYSParser.scala, app/connectors/httpParsers/GetDividendsIncomeTYSParser.scala, app/services/CreateUpdateDividendsIncomeService.scala, app/services/DeleteDividendsIncomeDataService.scala, app/services/GetDividendsIncomeService.scala, conf/application.conf, it/connectors/CreateUpdateStockDividendsIncomeTYSConnectorSpec.scala, it/connectors/DeleteDividendsIncomeDataTYSConnectorISpec.scala, it/connectors/GetDividendsIncomeTYSConnectorISpec.scala, project/AppDependencies.scala, project/plugins.sbt, test/services/CreateUpdateDividendsIncomeServiceSpec.scala, test/services/DeleteDividendsIncomeDataServiceSpec.scala, test/services/GetDividendsIncomeServiceSpec.scala
=> SASS-5772 Create connectors for API 1906 1907 1908

app/connectors/httpParsers/GetAnnualIncomeSourcePeriodHttpParser.scala
=> SASS-8323 added log to get IFS response

app/connectors/httpParsers/SubmittedDividendsHttpParser.scala, it/test/connectors/SubmittedDividendsConnectorSpec.scala
=> SASS-8323 Updated submitted dividends parser to match with DES response

app/config/AppConfig.scala, test/services/CommonTaskListServiceSpec.scala, test/support/stubs/AppConfigStub.scala
=> SASS-9233: Update urls

app/services/CommonTaskListService.scala, test/services/CommonTaskListServiceSpec.scala
Add url for new CYA page in mini journey.
=> SASS-9627: Add new CYA url, refactor

app/services/CommonTaskListService.scala, test/services/CommonTaskListServiceSpec.scala
=> SASS-9634: Updated other Uk dividends amount CYA URL

app/services/CommonTaskListService.scala, test/services/CommonTaskListServiceSpec.scala
=> SASS-9633: Update url for new CYA page

app/services/CommonTaskListService.scala, test/services/CommonTaskListServiceSpec.scala
=> SASS-9636: Updated close company loan dividends amount CYA URL

app/config/AppConfig.scala, app/models/mongo/DividendsUserDataModel.scala, app/models/mongo/StockDividendsUserDataModel.scala, app/repositories/DividendsUserDataRepository.scala, app/repositories/StockDividendsUserDataRepository.scala, app/repositories/UserDataRepository.scala, conf/application.conf, it/test/repositories/DividendsUserDataRepositoryISpec.scala, it/test/utils/IntegrationTest.scala, test/config/MockAppConfig.scala, test/support/stubs/AppConfigStub.scala
When Time To Live (TTL) has been set then data is stored in the database, the data should be remove once the TTL has expired.
Linked to main ticket SASS-9611
=> SASS-10237: Updated Models, Repository with lastUpdated formatting

app/config/AppConfig.scala, app/services/CommonTaskListService.scala, conf/application.conf, project/plugins.sbt, test/config/MockAppConfig.scala, test/services/CommonTaskListServiceSpec.scala, test/support/stubs/AppConfigStub.scala
=> SASS-10502 Update mock app config base url to reflect real value. Update tests in CommonTaskListServiceSpec to handle feature switch correctly

app/config/AppConfig.scala, app/services/CommonTaskListService.scala, conf/application.conf, project/plugins.sbt, test/config/MockAppConfig.scala, test/services/CommonTaskListServiceSpec.scala, test/support/stubs/AppConfigStub.scala
=> SASS-10502

app/config/AppConfig.scala, conf/application.conf, it/test/utils/IntegrationTest.scala, test/utils/AesGcmAdCryptoSpec.scala
=> SASS-10720 Added useEncryption to feature-switch

app/controllers/predicates/AuthorisedAction.scala, test/controllers/predicates/AuthorisedActionSpec.scala
=> [SASS-10755] Update AuthAction exception handling and update logging levels

app/common/EnrolmentCommon.scala, app/config/AppConfig.scala, app/config/CryptoProvider.scala, app/controllers/predicates/AuthorisedAction.scala, app/models/User.scala, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/common/EnrolmentCommonSpec.scala, test/config/MockAppConfig.scala, test/controllers/CommonTaskListControllerSpec.scala, test/controllers/predicates/AuthorisedActionSpec.scala, test/support/stubs/AppConfigStub.scala, test/utils/TestUtils.scala
=> SASS-11310 - EMA disabled
